print('Click Run to run the final project you will build')
print('Welcome to Band Name Generator')
city = input('What is the name of the city you grew up in?\n')
pet_name = input("What is your pet's name?\n")
print('Your band name is: ' , city + " " + pet_name )